---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.zabbix.io
  resources:
  - zabbixes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.zabbix.io
  resources:
  - zabbixes/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.zabbix.io
  resources:
  - zabbixes/status
  verbs:
  - get
  - patch
  - update
